# Generated by Django 3.0.6 on 2020-05-08 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_nivel_escolar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome')),
                ('nivel_escolar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='app_nivel_escolar.NivelEscolar', verbose_name='Nível')),
            ],
            options={
                'verbose_name': 'Série Escolar',
                'verbose_name_plural': 'Séries Escolares',
            },
        ),
    ]
