"""
Django settings for mundodosaber project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%52(!fxt^yfa_3$3*xhfy&*oliuedi2!*wukk+n$6^e75hp(@$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','127.0.0.1','*','cemundosaber.pythoanywhere.com'] #


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms', #
    'app_core', #
    'app_nivel_escolar', #
    'app_serie_escolar', #
    'app_material', #
    'app_lembrete', #
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mundodosaber.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mundodosaber.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Maceio'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
# VARIÁVEIS DE AMBIENTE
STATIC_URL = '/static/' #

# https://stackoverflow.com/questions/24022558/differences-between-staticfiles-dir-static-root-and-media-root
# STATIC_ROOT = os.path.join(BASE_DIR, 'static/') # Não serve em desenvolvimento
# Serve apenas para produção, não funciona em desenvolvimento, nem mesmo que adicione no url path se debug true, como o caso de arquivos de media
# Inicialmente deverá estar vazio (tanto em produção comoe em desenvolvimento)
# Irá concentrar os arquivos estáticos em produção neste diretório após o comando collectstatic para o servidor web localizá-lo após setá-lo no próprio servidor web
if not DEBUG: 
    STATIC_ROOT = 'static/' #

STATICFILES_DIRS = [
  os.path.join(BASE_DIR, 'mundodosaber/static/'), # Informa para coletar arquivos estáticos em outros diretórios que não seja de uma aplicação, dentro da pasta do projeto por exemplo, o collectstatic leva depois para static
] #

MEDIA_URL = '/media/' #
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/') #
LOGIN_REDIRECT_URL = '/'  #
LOGIN_URL = '/usuario/login'  # Se colocar aqui não precisa colocar login_url em todas views que necessitar
CRISPY_TEMPLATE_PACK = 'bootstrap4' #
