# Generated by Django 3.0.6 on 2020-05-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_remoto', models.CharField(blank=True, max_length=50, verbose_name='REMOTE_ADDR')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='HTTP_HOST')),
                ('navegador', models.CharField(blank=True, max_length=255, verbose_name='HTTP_USER_AGENT')),
                ('data_hora_acesso', models.DateTimeField(blank=True, null=True, verbose_name='DATA HORA ACESSO')),
            ],
            options={
                'verbose_name': 'Acesso',
                'verbose_name_plural': 'Acessos',
            },
        ),
    ]
