# Generated by Django 3.0.6 on 2020-05-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acesso',
            old_name='navegador',
            new_name='agente_cliente_navegador',
        ),
        migrations.RenameField(
            model_name='acesso',
            old_name='host',
            new_name='host_cliente',
        ),
        migrations.RenameField(
            model_name='acesso',
            old_name='ip_remoto',
            new_name='ip_cliente',
        ),
        migrations.AddField(
            model_name='acesso',
            name='ip_cliente_x_forwarded_primeiro',
            field=models.CharField(blank=True, max_length=50, verbose_name='REMOTE_X_FORWARDED_FOR_PRIMEIRO'),
        ),
        migrations.AddField(
            model_name='acesso',
            name='ip_cliente_x_forwarded_ultimo',
            field=models.CharField(blank=True, max_length=50, verbose_name='REMOTE_X_FORWARDED_FOR_ULTIMO'),
        ),
    ]
