# Generated by Django 3.0.6 on 2020-05-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_auto_20200508_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='agente_cliente_navegador',
            field=models.CharField(max_length=255, null=True, verbose_name='HTTP_USER_AGENT'),
        ),
        migrations.AlterField(
            model_name='acesso',
            name='host_cliente',
            field=models.CharField(max_length=255, null=True, verbose_name='HTTP_HOST'),
        ),
        migrations.AlterField(
            model_name='acesso',
            name='ip_cliente',
            field=models.CharField(max_length=50, null=True, verbose_name='REMOTE_ADDR'),
        ),
        migrations.AlterField(
            model_name='acesso',
            name='ip_cliente_x_forwarded_primeiro',
            field=models.CharField(max_length=50, null=True, verbose_name='REMOTE_X_FORWARDED_FOR_PRIMEIRO'),
        ),
        migrations.AlterField(
            model_name='acesso',
            name='ip_cliente_x_forwarded_ultimo',
            field=models.CharField(max_length=50, null=True, verbose_name='REMOTE_X_FORWARDED_FOR_ULTIMO'),
        ),
    ]
