# Generated by Django 3.0.6 on 2020-05-10 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True, verbose_name='Título')),
                ('conteudo', models.CharField(max_length=500, verbose_name='Conteúdo')),
                ('visivel', models.CharField(choices=[('S', 'Sim'), ('N', 'NãO')], default='S', max_length=1, verbose_name='Visível')),
                ('data_hora_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Publicado em')),
                ('data_hora_alteracao', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lembretes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Lembrete',
                'verbose_name_plural': 'Lembretes',
            },
        ),
    ]
