# Generated by Django 3.0.6 on 2020-05-10 23:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_lembrete', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Material',
            new_name='Lembrete',
        ),
    ]
