# Generated by Django 3.0.6 on 2020-05-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lembrete', '0002_auto_20200510_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembrete',
            name='visivel',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=1, verbose_name='Visível'),
        ),
    ]
