# Generated by Django 3.0.6 on 2020-05-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lembrete', '0003_auto_20200510_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lembrete',
            name='visivel',
        ),
        migrations.AddField(
            model_name='lembrete',
            name='tornar_visivel',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=1, verbose_name='Tornar Visível'),
        ),
    ]
