# Generated by Django 3.0.6 on 2020-05-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lembrete', '0005_auto_20200511_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lembrete',
            old_name='tornar_visivel',
            new_name='visivel',
        ),
    ]
