# Generated by Django 3.0.6 on 2020-05-08 21:44

import app_material.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_nivel_escolar', '0001_initial'),
        ('app_serie_escolar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True, verbose_name='Título')),
                ('arquivo', models.FileField(upload_to=app_material.models.user_directory_path, verbose_name='Arquivo')),
                ('data_hora_upload', models.DateTimeField(auto_now_add=True, verbose_name='Publicado em')),
                ('data_hora_alteracao', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('nivel_escolar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiais', to='app_nivel_escolar.NivelEscolar', verbose_name='Nível')),
                ('serie_escolar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiais', to='app_serie_escolar.SerieEscolar', verbose_name='Série')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiais', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
            },
        ),
    ]
