# Generated by Django 3.0.6 on 2020-05-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='visivel',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'NãO')], default='S', max_length=1, verbose_name='Visível'),
        ),
    ]
